# Generated by Django 5.1.6 on 2025-03-30 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('status', models.CharField(choices=[('awaiting', 'Ожидает'), ('cancelled', 'Отменен'), ('paid', 'Оплачен')], default='awaiting', max_length=10, verbose_name='Статус оплаты')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Используется в ссылке на оплату', max_digits=10, null=True, verbose_name='Сумма')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок оплаты')),
                ('payment_url', models.URLField(blank=True, max_length=2000, null=True, verbose_name='Ссылка на оплату')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
