# Generated by Django 5.1.6 on 2025-04-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_cost_order_comment_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_url',
        ),
    ]
