# Generated by Django 5.1.6 on 2025-04-20 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_points', '0004_alter_area_options_alter_deliverypoint_options_and_more'),
        ('orders', '0003_remove_order_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery_points.deliverypoint', verbose_name='Адрес достаки'),
        ),
    ]
