# Generated by Django 5.1.6 on 2025-04-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
