# Generated by Django 5.1.6 on 2025-04-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.CharField(choices=[('none', 'Без НДС'), ('vat0', 'НДС по ставке 0%'), ('vat10', 'НДС чека по ставке 10%'), ('vat110', 'НДС чека по расчетной ставке 10/110'), ('vat20', 'НДС чека по ставке 20%'), ('vat120', 'НДС чека по расчетной ставке 20/120'), ('vat5', 'НДС по ставке 5%'), ('vat7', 'НДС по ставке 7%'), ('vat105', 'НДС чека по расчетной ставке 5/105'), ('vat107', 'НДС чека по расчетной ставке 7/107')], default='none', max_length=10, verbose_name='Налоговая ставка'),
        ),
    ]
