# Generated by Django 5.1.6 on 2025-04-06 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_points', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('house_number', models.CharField(max_length=200, verbose_name='Номер дома')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_points', to='users.customer', verbose_name='Клиент')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_points', to='delivery_points.street', verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Точка доставки',
                'verbose_name_plural': 'Точки доставки',
            },
        ),
    ]
