# Generated by Django 5.1.6 on 2025-04-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_points', '0002_deliverypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypoint',
            name='entrance_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер подъезда'),
            preserve_default=False,
        ),
    ]
