# Generated by Django 5.1.6 on 2025-04-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_points', '0003_deliverypoint_entrance_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('name',), 'verbose_name': 'Зона доставки', 'verbose_name_plural': 'Зоны доставки'},
        ),
        migrations.AlterModelOptions(
            name='deliverypoint',
            options={'ordering': ('street__name',), 'verbose_name': 'Точка доставки', 'verbose_name_plural': 'Точки доставки'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'ordering': ('name',), 'verbose_name': 'Улица', 'verbose_name_plural': 'Улицы'},
        ),
        migrations.AddField(
            model_name='deliverypoint',
            name='actual',
            field=models.BooleanField(default=True, verbose_name='Текущий'),
        ),
    ]
