# Generated by Django 5.1.6 on 2025-04-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_points', '0004_alter_area_options_alter_deliverypoint_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='exists_entrance',
            field=models.BooleanField(default=True, verbose_name='Наличие подъездов'),
        ),
    ]
