# Generated by Django 5.1.6 on 2025-04-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_points', '0005_area_exists_entrance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypoint',
            name='entrance_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер подъезда'),
        ),
    ]
