# Generated by Django 5.1.6 on 2025-04-06 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Введите номер в формате +71234567890 или 89123456789', regex='^(?:\\+7|8)\\d{10}$')]),
        ),
    ]
