# Generated by Django 5.1.6 on 2025-04-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Карта'), ('online', 'Онлайн')], max_length=10, null=True, verbose_name='Способ оплаты'),
        ),
    ]
