# Generated by Django 5.1.6 on 2025-04-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_cart_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Карта'), ('robokassa', 'Робокасса')], max_length=10, null=True, verbose_name='Способ оплаты'),
        ),
    ]
