# Generated by Django 5.1.6 on 2025-04-11 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_cart_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Фиксируется в момент добалвения в корзину', max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.cart', verbose_name='Клиент'),
        ),
    ]
