# Generated by Django 5.1.6 on 2025-04-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Фиксируется в момент добавления в корзину', max_digits=10, verbose_name='Цена'),
        ),
    ]
