# Generated by Django 5.1.6 on 2026-01-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_cartitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('text', models.TextField(max_length=2500, verbose_name='Текст')),
                ('is_actual', models.BooleanField(default=False, verbose_name='Актуальна')),
            ],
            options={
                'verbose_name': 'Согласие на обработку ПД',
                'verbose_name_plural': 'Согласия на обработку ПД',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='gdpr_accepted',
            field=models.BooleanField(default=False, help_text='Статус согласия на обработку перс. данных', verbose_name='Согласие на ПД'),
        ),
    ]
