# Generated by Django 5.1.6 on 2026-02-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_gdpr_customer_gdpr_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='receipt_method_type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], default='pickup', max_length=10, verbose_name='Способ получения'),
        ),
        migrations.AlterField(
            model_name='gdpr',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
    ]
